spring:
  profiles:
    active:
      - dev

---

spring:
  port: 8082
  profiles: dev
  application:
    name: configservice-dev


---

spring:
  profiles: test
  application:
    name: configservice-test
