spring:
  profiles:
    active:
      - dev

---

server: 
  port: 8082


spring:
  profiles: dev
  application:
    name: configservice-dev
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


---

server: 
  port: 8083


spring:
  profiles: test
  application:
    name: configservice-test
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
